-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "id" DROP NOT NULL,
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "author" DROP NOT NULL,
ALTER COLUMN "created_utc" DROP NOT NULL,
ALTER COLUMN "full_link" DROP NOT NULL,
ALTER COLUMN "num_comments" DROP NOT NULL,
ALTER COLUMN "score" DROP NOT NULL;
